### ISSUE TITLE
Work on frontend and demo (2 weeks - 3 weeks)

### ISSUE THREAD

**Issue by SwimSwag10** [SwimSwag10/my-patient-coverage#16]
- [ ] Make sure the csv is structures appropriately for Claim & Payment using Pappaparse
- [ ] Create the displayed claims/payments based on search criteria.
> Should the search be a frontend search for the items already in the requested items (in this case it would be 10 payments), the search should be an entirely new fetch request, or the request fetching the data would have a "params" attached to the searchPayment fetch?
- [ ] Make sure we have the actual data (dependent on the proxy Lambda).
