### ISSUE TITLE
get a signup function working to stick users in the Dynamo table with encrypted Delta credentials (5 weeks)

### ISSUE THREAD

**Issue by SwimSwag10** [SwimSwag10/my-patient-coverage#17]
- [ ] Create function to add users into Dynamo table 2 (weeks)
- [ ] Schema (1 week - 2 weeks)
- [ ] Authenticate user (3 weeks)
